services:
  db:
    image: postgres:15-alpine
    container_name: antam_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: antam_kitchen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: antam_api
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/antam_kitchen
      - PORT=3001
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: antam_web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - api

volumes:
  postgres_data:
